# /etc/rsyslog.d/bunnywaf.conf

input(
    type="imfile"
    File="/opt/bunnywaf/logs/bunnywaf.log"
    Tag="BunnyWAF"
    Facility="local6"
    Severity="info"
    PersistStateInterval="100"
)

if $programname == "BunnyWAF" then {
    action(
        type="omfwd"
        Target="<SYSLOG-HOST>"
        Port="514"
        Protocol="tcp"
        TCP_Framing="octet-counted"
        KeepAlive="on"
        Action.ResumeRetryCount="-1"
    )
    stop
}

