[general]

# Supported: apache, nginx, iis
log_type = apache

# Access log to monitor
access_log = /var/log/httpd/access_log

# Detection signatures
signature_file = signatures/bunny-pattern.txt

# BunnyWAF alert log
alert_log = logs/bunnywaf.log

